CREATE TABLE exam_question_source (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_name VARCHAR(128) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    original_url VARCHAR(1024) NULL,
    copyright_status ENUM('ORIGINAL', 'AUTHORIZED', 'PUBLIC_OFFICIAL', 'UNVERIFIED', 'PROHIBITED') NOT NULL,
    review_status ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'DISABLED') NOT NULL DEFAULT 'DRAFT',
    copyright_note TEXT NULL,
    reviewed_by BIGINT UNSIGNED NULL,
    review_comment TEXT NULL,
    reviewed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_exam_question_source_review_status (review_status),
    CONSTRAINT fk_exam_question_source_reviewer FOREIGN KEY (reviewed_by) REFERENCES sys_admin (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试题源及版权审核';

CREATE TABLE exam_import_batch (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    file_name VARCHAR(255) NOT NULL,
    file_format VARCHAR(32) NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    imported_by BIGINT UNSIGNED NOT NULL,
    status ENUM('UPLOADED', 'VALIDATED', 'IMPORTED', 'REJECTED') NOT NULL DEFAULT 'UPLOADED',
    total_rows INT UNSIGNED NOT NULL DEFAULT 0,
    success_rows INT UNSIGNED NOT NULL DEFAULT 0,
    failed_rows INT UNSIGNED NOT NULL DEFAULT 0,
    structure_errors JSON NULL,
    duplicate_warnings JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_exam_import_batch_source (source_id),
    KEY idx_exam_import_batch_importer_created (imported_by, created_at),
    CONSTRAINT fk_exam_import_batch_source FOREIGN KEY (source_id) REFERENCES exam_question_source (id),
    CONSTRAINT fk_exam_import_batch_importer FOREIGN KEY (imported_by) REFERENCES sys_admin (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试题库导入批次';

CREATE TABLE exam_question_group (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_type ENUM('DIALOGUE', 'READING') NOT NULL,
    title VARCHAR(255) NOT NULL,
    instruction TEXT NULL,
    content LONGTEXT NOT NULL,
    shared_options JSON NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    difficulty TINYINT UNSIGNED NOT NULL,
    knowledge_points JSON NULL,
    content_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_status ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'DISABLED') NOT NULL DEFAULT 'DRAFT',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_exam_question_group_source (source_id),
    KEY idx_exam_question_group_fingerprint (content_fingerprint),
    KEY idx_exam_question_group_available (group_type, review_status, enabled),
    CONSTRAINT fk_exam_question_group_source FOREIGN KEY (source_id) REFERENCES exam_question_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试题组';

CREATE TABLE exam_question (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_id BIGINT UNSIGNED NULL,
    question_type ENUM('DIALOGUE_BLANK', 'READING', 'VOCABULARY', 'GRAMMAR', 'TRANSLATION', 'WRITING') NOT NULL,
    stem LONGTEXT NOT NULL,
    options JSON NULL,
    correct_answer JSON NULL,
    explanation LONGTEXT NULL,
    reference_answer LONGTEXT NULL,
    sample_answer LONGTEXT NULL,
    scoring_rubric JSON NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    group_sort_order INT UNSIGNED NULL,
    difficulty TINYINT UNSIGNED NOT NULL,
    knowledge_points JSON NULL,
    content_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    review_status ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'DISABLED') NOT NULL DEFAULT 'DRAFT',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_exam_question_group_order (group_id, group_sort_order),
    KEY idx_exam_question_source (source_id),
    KEY idx_exam_question_fingerprint (content_fingerprint),
    KEY idx_exam_question_available (question_type, review_status, enabled),
    CONSTRAINT fk_exam_question_group FOREIGN KEY (group_id) REFERENCES exam_question_group (id),
    CONSTRAINT fk_exam_question_source FOREIGN KEY (source_id) REFERENCES exam_question_source (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试题目';

CREATE TABLE exam_blueprint (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    blueprint_code VARCHAR(64) NOT NULL,
    blueprint_name VARCHAR(128) NOT NULL,
    version VARCHAR(32) NOT NULL,
    duration_minutes INT UNSIGNED NOT NULL,
    total_score DECIMAL(6, 2) UNSIGNED NOT NULL,
    status ENUM('ENABLED', 'DISABLED') NOT NULL DEFAULT 'ENABLED',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_blueprint_code_version (blueprint_code, version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试组卷蓝图';

CREATE TABLE exam_blueprint_section (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    blueprint_id BIGINT UNSIGNED NOT NULL,
    section_order INT UNSIGNED NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    group_count INT UNSIGNED NOT NULL DEFAULT 0,
    answer_item_count INT UNSIGNED NOT NULL,
    score_per_item DECIMAL(6, 2) UNSIGNED NOT NULL,
    subjective TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_blueprint_section_order (blueprint_id, section_order),
    CONSTRAINT fk_exam_blueprint_section_blueprint FOREIGN KEY (blueprint_id) REFERENCES exam_blueprint (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试蓝图部分';

CREATE TABLE exam_paper (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    paper_no VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    blueprint_id BIGINT UNSIGNED NOT NULL,
    blueprint_version_snapshot VARCHAR(32) NOT NULL,
    status ENUM('IN_PROGRESS', 'SUBMITTED', 'AUTO_SUBMITTED') NOT NULL DEFAULT 'IN_PROGRESS',
    started_at DATETIME(3) NOT NULL,
    due_at DATETIME(3) NOT NULL,
    submitted_at DATETIME(3) NULL,
    objective_score DECIMAL(6, 2) UNSIGNED NULL,
    translation_self_score TINYINT UNSIGNED NULL,
    writing_self_score TINYINT UNSIGNED NULL,
    self_score_total DECIMAL(6, 2) UNSIGNED NULL,
    version INT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_paper_paper_no (paper_no),
    KEY idx_exam_paper_user_status (user_id, status),
    KEY idx_exam_paper_blueprint (blueprint_id),
    CONSTRAINT fk_exam_paper_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_exam_paper_blueprint FOREIGN KEY (blueprint_id) REFERENCES exam_blueprint (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试试卷';

CREATE TABLE exam_paper_group_snapshot (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paper_id BIGINT UNSIGNED NOT NULL,
    original_group_id BIGINT UNSIGNED NOT NULL,
    section_order INT UNSIGNED NOT NULL,
    group_order INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    instruction TEXT NULL,
    content LONGTEXT NOT NULL,
    shared_options JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_paper_group_snapshot_order (paper_id, section_order, group_order),
    KEY idx_exam_paper_group_snapshot_original (original_group_id),
    CONSTRAINT fk_exam_paper_group_snapshot_paper FOREIGN KEY (paper_id) REFERENCES exam_paper (id),
    CONSTRAINT fk_exam_paper_group_snapshot_original FOREIGN KEY (original_group_id) REFERENCES exam_question_group (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='试卷题组快照';

CREATE TABLE exam_paper_item_snapshot (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paper_id BIGINT UNSIGNED NOT NULL,
    paper_group_snapshot_id BIGINT UNSIGNED NULL,
    original_question_id BIGINT UNSIGNED NOT NULL,
    section_order INT UNSIGNED NOT NULL,
    item_order INT UNSIGNED NOT NULL,
    question_type VARCHAR(32) NOT NULL,
    stem LONGTEXT NOT NULL,
    options JSON NULL,
    correct_answer JSON NULL,
    explanation LONGTEXT NULL,
    reference_answer LONGTEXT NULL,
    sample_answer LONGTEXT NULL,
    scoring_rubric JSON NULL,
    knowledge_points JSON NULL,
    score DECIMAL(6, 2) UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_paper_item_snapshot_order (paper_id, section_order, item_order),
    KEY idx_exam_paper_item_snapshot_original (original_question_id),
    KEY idx_exam_paper_item_snapshot_group (paper_group_snapshot_id),
    CONSTRAINT fk_exam_paper_item_snapshot_paper FOREIGN KEY (paper_id) REFERENCES exam_paper (id),
    CONSTRAINT fk_exam_paper_item_snapshot_group FOREIGN KEY (paper_group_snapshot_id) REFERENCES exam_paper_group_snapshot (id),
    CONSTRAINT fk_exam_paper_item_snapshot_original FOREIGN KEY (original_question_id) REFERENCES exam_question (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='试卷题目快照';

CREATE TABLE exam_answer (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paper_id BIGINT UNSIGNED NOT NULL,
    paper_item_id BIGINT UNSIGNED NOT NULL,
    answer_content JSON NULL,
    answer_version INT UNSIGNED NOT NULL DEFAULT 0,
    saved_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    objectively_correct TINYINT(1) NULL,
    earned_score DECIMAL(6, 2) UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_answer_paper_item (paper_id, paper_item_id),
    CONSTRAINT fk_exam_answer_paper FOREIGN KEY (paper_id) REFERENCES exam_paper (id),
    CONSTRAINT fk_exam_answer_item FOREIGN KEY (paper_item_id) REFERENCES exam_paper_item_snapshot (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试答案';

CREATE TABLE exam_wrong_record (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    paper_id BIGINT UNSIGNED NOT NULL,
    paper_item_id BIGINT UNSIGNED NOT NULL,
    original_question_id BIGINT UNSIGNED NOT NULL,
    wrong_answer JSON NULL,
    knowledge_points JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_wrong_record_paper_item (paper_id, paper_item_id),
    KEY idx_exam_wrong_record_user_created (user_id, created_at),
    KEY idx_exam_wrong_record_question (original_question_id),
    CONSTRAINT fk_exam_wrong_record_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_exam_wrong_record_paper FOREIGN KEY (paper_id) REFERENCES exam_paper (id),
    CONSTRAINT fk_exam_wrong_record_item FOREIGN KEY (paper_item_id) REFERENCES exam_paper_item_snapshot (id),
    CONSTRAINT fk_exam_wrong_record_question FOREIGN KEY (original_question_id) REFERENCES exam_question (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='考试错题记录';
