-- Templates are append-only content. Corrections insert a new version; only publication
-- status may change. Learner attempts continue to own their independent V12 snapshots.
CREATE TABLE exam_fixed_paper (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    paper_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    version INT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    blueprint_id BIGINT UNSIGNED NOT NULL,
    blueprint_version_snapshot VARCHAR(32) NOT NULL,
    duration_minutes INT UNSIGNED NOT NULL,
    total_score DECIMAL(6, 2) UNSIGNED NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    source_declaration LONGTEXT NOT NULL,
    content_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    display_order INT UNSIGNED NOT NULL,
    status ENUM('DRAFT', 'PUBLISHED', 'DISABLED') NOT NULL DEFAULT 'DRAFT',
    published_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_fixed_paper_code_version (paper_code, version),
    UNIQUE KEY uk_exam_fixed_paper_fingerprint (content_fingerprint),
    KEY idx_exam_fixed_paper_publication (status, display_order, paper_code, version),
    KEY idx_exam_fixed_paper_blueprint (blueprint_id),
    KEY idx_exam_fixed_paper_source (source_id),
    CONSTRAINT fk_exam_fixed_paper_blueprint FOREIGN KEY (blueprint_id) REFERENCES exam_blueprint (id),
    CONSTRAINT fk_exam_fixed_paper_source FOREIGN KEY (source_id) REFERENCES exam_question_source (id),
    CONSTRAINT ck_exam_fixed_paper_version CHECK (version > 0),
    CONSTRAINT ck_exam_fixed_paper_order CHECK (display_order > 0),
    CONSTRAINT ck_exam_fixed_paper_duration CHECK (duration_minutes > 0 AND total_score > 0),
    CONSTRAINT ck_exam_fixed_paper_publication CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='固定原创模拟试卷模板，修订须新增版本';

CREATE TABLE exam_fixed_paper_group (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fixed_paper_id BIGINT UNSIGNED NOT NULL,
    original_group_id BIGINT UNSIGNED NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    content_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    section_order INT UNSIGNED NOT NULL,
    group_order INT UNSIGNED NOT NULL,
    group_type ENUM('DIALOGUE', 'READING') NOT NULL,
    title VARCHAR(255) NOT NULL,
    instruction TEXT NULL,
    content LONGTEXT NOT NULL,
    shared_options JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_fixed_group_order (fixed_paper_id, section_order, group_order),
    UNIQUE KEY uk_exam_fixed_group_original (fixed_paper_id, original_group_id),
    UNIQUE KEY uk_exam_fixed_group_scope (fixed_paper_id, section_order, id),
    KEY idx_exam_fixed_group_original (original_group_id),
    KEY idx_exam_fixed_group_source (source_id),
    KEY idx_exam_fixed_group_fingerprint (content_fingerprint),
    CONSTRAINT fk_exam_fixed_group_paper FOREIGN KEY (fixed_paper_id) REFERENCES exam_fixed_paper (id),
    CONSTRAINT fk_exam_fixed_group_original FOREIGN KEY (original_group_id) REFERENCES exam_question_group (id),
    CONSTRAINT fk_exam_fixed_group_source FOREIGN KEY (source_id) REFERENCES exam_question_source (id),
    CONSTRAINT ck_exam_fixed_group_order CHECK (section_order > 0 AND group_order > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='固定试卷题组冻结快照';

CREATE TABLE exam_fixed_paper_item (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fixed_paper_id BIGINT UNSIGNED NOT NULL,
    fixed_paper_group_id BIGINT UNSIGNED NULL,
    original_question_id BIGINT UNSIGNED NOT NULL,
    source_id BIGINT UNSIGNED NOT NULL,
    content_fingerprint CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    section_order INT UNSIGNED NOT NULL,
    item_order INT UNSIGNED NOT NULL,
    question_type ENUM('DIALOGUE_BLANK', 'READING', 'VOCABULARY', 'GRAMMAR', 'TRANSLATION', 'WRITING') NOT NULL,
    stem LONGTEXT NOT NULL,
    options JSON NULL,
    correct_answer JSON NULL,
    explanation LONGTEXT NULL,
    reference_answer LONGTEXT NULL,
    sample_answer LONGTEXT NULL,
    scoring_rubric JSON NULL,
    knowledge_points JSON NULL,
    score DECIMAL(6, 2) UNSIGNED NOT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_exam_fixed_item_order (fixed_paper_id, section_order, item_order),
    UNIQUE KEY uk_exam_fixed_item_original (fixed_paper_id, original_question_id),
    KEY idx_exam_fixed_item_group_scope (fixed_paper_id, section_order, fixed_paper_group_id),
    KEY idx_exam_fixed_item_original (original_question_id),
    KEY idx_exam_fixed_item_source (source_id),
    KEY idx_exam_fixed_item_fingerprint (content_fingerprint),
    CONSTRAINT fk_exam_fixed_item_paper FOREIGN KEY (fixed_paper_id) REFERENCES exam_fixed_paper (id),
    CONSTRAINT fk_exam_fixed_item_group FOREIGN KEY (fixed_paper_id, section_order, fixed_paper_group_id)
        REFERENCES exam_fixed_paper_group (fixed_paper_id, section_order, id),
    CONSTRAINT fk_exam_fixed_item_original FOREIGN KEY (original_question_id) REFERENCES exam_question (id),
    CONSTRAINT fk_exam_fixed_item_source FOREIGN KEY (source_id) REFERENCES exam_question_source (id),
    CONSTRAINT ck_exam_fixed_item_order CHECK (section_order > 0 AND item_order > 0 AND score > 0),
    CONSTRAINT ck_exam_fixed_item_group CHECK (
        (question_type IN ('DIALOGUE_BLANK', 'READING') AND fixed_paper_group_id IS NOT NULL)
        OR (question_type IN ('VOCABULARY', 'GRAMMAR', 'TRANSLATION', 'WRITING') AND fixed_paper_group_id IS NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='固定试卷题目冻结快照，仅服务端读取答案及参考材料';
